### ISSUE TITLE
実行エラー

### ISSUE THREAD

**Issue by kitec-tanaka** [farend/redmine-ubuntu-ansible#1]
実行したところ、次の様なエラーがでました。

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1454670833.49-216265699020264/subversion", line 2194, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1454670833.49-216265699020264/subversion", line 239, in main
    before = svn.get_revision()
  File "/root/.ansible/tmp/ansible-tmp-1454670833.49-216265699020264/subversion", line 167, in get_revision
    rev = re.search(r'^Revision:.*$', text, re.MULTILINE).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "subversion"}, "parsed": false}

**Comment by vividtone** [comment]
回答遅くなってすみません。Ansible 2.1.0の問題だったようです。
https://github.com/ansible/ansible/issues/14704
